- repo: https://github.com/rapidsai/frigate
  rev: v0.4.0 #  pre-commit autoupdate  - to keep the version up to date
  hooks:
    - id: frigate
      args:
        - --output=./charts/pact-broker/README.md
        - --no-credits
        - --no-deps