apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{ end }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}

spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
